name: NASA Project CI
on:
   push:
<<<<<<< HEAD
      branches: main
   pull_request:
      branches: main
=======
      branches: main 
>>>>>>> aa06b0fe9f91890963fc7c4cec2f45bab733f5d1
jobs:
   build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js version 18
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        - run: npm install
        - run: npm run build --preficx client
        
